const mongoose = require('mongoose');
const Destination = require('./models/Destination');
const Hotel = require('./models/Hotel');
const Restaurant = require('./models/Restaurant');
require('dotenv').config();

const destinations = [
  { id:"everest", name:"Mount Everest & Base Camp", province:"Province No. 1", category:"mountain", image:"https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80", description:"The world's highest peak at 8,849 m. The classic Everest Base Camp trek takes you through Sherpa villages like Namche Bazaar and Tengboche, past Buddhist monasteries, across suspension bridges draped in prayer flags, and through stunning glacial landscapes.", latitude:27.9881, longitude:86.9250, bestSeason:"Mar–May, Sep–Nov", entryFee:"NPR 11,000 (TIMS + permit)", activities:["Trekking","Mountaineering","Photography","Cultural Tours"] },
  { id:"annapurna", name:"Annapurna Circuit", province:"Gandaki Province", category:"mountain", image:"https://images.unsplash.com/photo-1571401835393-8c5f35328320?w=800&q=80", description:"One of the world's greatest treks, circumnavigating the Annapurna massif and crossing Thorong La Pass at 5,416 m.", latitude:28.5971, longitude:84.1060, bestSeason:"Oct–Nov, Mar–Apr", entryFee:"NPR 3,000 (ACAP permit)", activities:["Trekking","Camping","Photography","Homestay"] },
  { id:"boudhanath", name:"Boudhanath Stupa", province:"Bagmati Province", category:"heritage", image:"https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80", description:"One of the largest Buddhist stupas in the world and a UNESCO World Heritage Site.", latitude:27.7215, longitude:85.3620, bestSeason:"Year-round", entryFee:"NPR 400", activities:["Cultural Tours","Photography","Meditation","Shopping"] },
  { id:"pashupatinath", name:"Pashupatinath Temple", province:"Bagmati Province", category:"heritage", image:"https://images.unsplash.com/photo-1609348745238-e71a01a9eed0?w=800&q=80", description:"The most sacred Hindu temple in Nepal, dedicated to Lord Shiva on the banks of the holy Bagmati River.", latitude:27.7105, longitude:85.3487, bestSeason:"Year-round", entryFee:"NPR 1,000", activities:["Pilgrimage","Photography","Cultural Tours"] },
  { id:"pokhara", name:"Pokhara & Phewa Lake", province:"Gandaki Province", category:"lake", image:"https://images.unsplash.com/photo-1706323625285-648bb6825e03?w=800&q=80", description:"Nepal's adventure capital where Phewa Lake mirrors the snow-capped Annapurna peaks at sunrise.", latitude:28.2096, longitude:83.9856, bestSeason:"Sep–Nov, Mar–May", entryFee:"Free", activities:["Boating","Paragliding","Trekking","Zip-lining","Photography"] },
  { id:"chitwan", name:"Chitwan National Park", province:"Bagmati Province", category:"nature", image:"https://images.unsplash.com/photo-1571150825816-3b9c10640445?w=800&q=80", description:"A UNESCO World Heritage Site and one of Asia's finest wildlife reserves protecting the one-horned rhinoceros and Royal Bengal tiger.", latitude:27.5291, longitude:84.3542, bestSeason:"Oct–Mar", entryFee:"USD 25", activities:["Jungle Safari","Bird Watching","Canoe Ride","Elephant Bathing"] },
  { id:"lumbini", name:"Lumbini – Birthplace of Buddha", province:"Lumbini Province", category:"heritage", image:"https://images.unsplash.com/photo-1616166831462-48a3e9089c20?w=800&q=80", description:"The birthplace of Siddhartha Gautama and a UNESCO World Heritage Site with the Mayadevi Temple and ancient Ashoka Pillar.", latitude:27.4833, longitude:83.2761, bestSeason:"Oct–Mar", entryFee:"NPR 200", activities:["Pilgrimage","Meditation","Photography","Cultural Tours"] },
  { id:"rara", name:"Rara Lake", province:"Karnali Province", category:"lake", image:"https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80", description:"Nepal's largest and deepest lake hidden in the remote northwest at 2,990 m with sapphire-blue water.", latitude:29.5269, longitude:82.0883, bestSeason:"Apr–Jun, Sep–Nov", entryFee:"NPR 3,000", activities:["Trekking","Camping","Bird Watching","Photography"] },
  { id:"poonhill", name:"Ghorepani Poon Hill", province:"Gandaki Province", category:"mountain", image:"https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80", description:"The most popular short trek in Nepal with a panoramic sunrise over the Annapurna and Dhaulagiri ranges from 3,210 m.", latitude:28.4167, longitude:83.6833, bestSeason:"Mar–May, Sep–Nov", entryFee:"ACAP permit", activities:["Trekking","Sunrise Viewing","Photography","Rhododendron Forests"] },
  { id:"bhaktapur", name:"Bhaktapur Durbar Square", province:"Bagmati Province", category:"heritage", image:"https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=800&q=80", description:"The best-preserved medieval city in Kathmandu Valley and a UNESCO World Heritage Site with the 55-Window Palace.", latitude:27.6722, longitude:85.4281, bestSeason:"Oct–Mar", entryFee:"NPR 1,500", activities:["Cultural Tours","Photography","Pottery","Architecture"] },
  { id:"nagarkot", name:"Nagarkot", province:"Bagmati Province", category:"nature", image:"https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80", description:"A peaceful hill station at 2,175 m famous for its wide Himalayan sunrise panorama including Everest.", latitude:27.8010, longitude:85.5210, bestSeason:"Oct–Dec, Feb–Apr", entryFee:"Free", activities:["Sunrise Viewing","Hiking","Photography","Bird Watching"] },
  { id:"mustang", name:"Upper Mustang", province:"Gandaki Province", category:"heritage", image:"https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80", description:"The last forbidden kingdom closed to outsiders until 1992 with the walled city of Lo Manthang.", latitude:29.1833, longitude:83.9667, bestSeason:"May–Sep", entryFee:"USD 500 permit", activities:["Trekking","Cultural Tours","Monastery Visits","Photography"] },
  { id:"swayambhunath", name:"Swayambhunath (Monkey Temple)", province:"Bagmati Province", category:"heritage", image:"https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80", description:"Perched atop a wooded hill above Kathmandu, one of Nepal's oldest religious sites with the all-seeing eyes of the Buddha.", latitude:27.7149, longitude:85.2907, bestSeason:"Year-round", entryFee:"NPR 200", activities:["Photography","Sunset Views","Stairs Climb","Meditation"] },
  { id:"sarangkot", name:"Sarangkot", province:"Gandaki Province", category:"nature", image:"https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&q=80", description:"The famous ridge above Pokhara from which paragliders launch above Phewa Lake with the Annapurna giants as backdrop.", latitude:28.2500, longitude:83.9500, bestSeason:"Sep–Nov, Mar–May", entryFee:"Free", activities:["Paragliding","Sunrise Viewing","Photography","Hiking"] },
  { id:"gokyo", name:"Gokyo Lakes", province:"Province No. 1", category:"lake", image:"https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800&q=80", description:"Six turquoise glacial lakes at the base of Nepal's longest glacier with views of four 8000m peaks.", latitude:27.9667, longitude:86.6833, bestSeason:"Mar–May, Sep–Nov", entryFee:"Sagarmatha permit", activities:["Trekking","Photography","Lake Views","Peak Climbing"] },
  { id:"bardiya", name:"Bardia National Park", province:"Lumbini Province", category:"nature", image:"https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=800&q=80", description:"Nepal's largest national park in the western Terai with high tiger concentration and the Karnali River.", latitude:28.3833, longitude:81.3167, bestSeason:"Oct–Mar", entryFee:"USD 20–25", activities:["Safari","Tiger Tracking","Bird Watching","Tharu Culture"] },
  { id:"patan", name:"Patan Durbar Square", province:"Bagmati Province", category:"heritage", image:"https://images.unsplash.com/photo-1598346762291-aee88549193f?w=800&q=80", description:"The most artistically rich of the three royal squares in Kathmandu Valley with the finest museum in Nepal.", latitude:27.6722, longitude:85.3250, bestSeason:"Oct–Mar", entryFee:"NPR 1,000", activities:["Architecture","Photography","Art & Crafts","Museum"] },
  { id:"bandipur", name:"Bandipur Village", province:"Gandaki Province", category:"heritage", image:"https://images.unsplash.com/photo-1586348943529-beaae6c28db9?w=800&q=80", description:"A car-free Newari hilltop town frozen in the 19th century with traditional architecture and mountain views.", latitude:27.9333, longitude:84.4167, bestSeason:"Oct–Mar", entryFee:"Free", activities:["Village Walk","Photography","Sunset Views","Hiking"] },
  { id:"ilam", name:"Ilam Tea Gardens", province:"Koshi Province", category:"nature", image:"https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=800&q=80", description:"Nepal's premier tea-growing region in the eastern hills producing some of South Asia's finest Orthodox teas.", latitude:26.9167, longitude:87.9333, bestSeason:"Mar–May, Oct–Nov", entryFee:"Free", activities:["Tea Tasting","Factory Tour","Hiking","Photography"] },
  { id:"janakpur", name:"Janakpur – Janaki Mandir", province:"Madhesh Province", category:"heritage", image:"https://images.unsplash.com/photo-1545126913-da4f3c7ad3d1?w=800&q=80", description:"The birthplace of Goddess Sita with the magnificent Janaki Mandir temple built in 1911 in Mughal-Rajput style.", latitude:26.7333, longitude:85.9333, bestSeason:"Oct–Mar", entryFee:"Free", activities:["Pilgrimage","Mithila Art","Photography","Cultural Tours"] },
  { id:"gosainkunda", name:"Gosainkunda Lake", province:"Bagmati Province", category:"lake", image:"https://images.unsplash.com/photo-1439853949212-36589f9027c4?w=800&q=80", description:"A sacred alpine lake at 4,380 m where tens of thousands of pilgrims trek during Janai Purnima.", latitude:28.0833, longitude:85.6167, bestSeason:"May–Jun, Sep–Oct", entryFee:"Langtang permit", activities:["Pilgrimage","Trekking","Photography","High Altitude Walk"] },
  { id:"chandragiri", name:"Chandragiri Hills", province:"Bagmati Province", category:"nature", image:"https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&q=80", description:"A hill station accessible by cable car with sweeping views of Kathmandu Valley and the Himalayan chain.", latitude:27.6667, longitude:85.2000, bestSeason:"Oct–Mar", entryFee:"Cable car ticket", activities:["Cable Car Ride","Temple Visit","Photography","Valley Views"] },
  { id:"gorkha", name:"Gorkha Palace", province:"Gandaki Province", category:"heritage", image:"https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&q=80", description:"The ancestral home of Prithvi Narayan Shah who unified Nepal, with spectacular Himalayan views.", latitude:27.9833, longitude:84.6333, bestSeason:"Oct–Mar", entryFee:"NPR 500", activities:["History Tour","Hiking","Photography","Architecture"] },
  { id:"tansen", name:"Tansen (Palpa)", province:"Lumbini Province", category:"heritage", image:"https://images.unsplash.com/photo-1519125323398-675f0ddb6308?w=800&q=80", description:"A well-preserved Newari hilltop trading town famous for dhaka cloth weaving and bronze crafts.", latitude:27.8667, longitude:83.5500, bestSeason:"Oct–Mar", entryFee:"Free", activities:["Walking Tour","Architecture","Dhaka Weaving","Photography"] },
  { id:"langtang", name:"Langtang Valley", province:"Bagmati Province", category:"mountain", image:"https://images.unsplash.com/photo-1526772662000-3f88f10405ff?w=800&q=80", description:"The closest major trekking destination to Kathmandu, flanked by the 7,234-metre Langtang Lirung peak.", latitude:28.1667, longitude:85.6667, bestSeason:"Mar–May, Sep–Nov", entryFee:"Langtang permit", activities:["Trekking","Monastery Visit","Cheese Factory","Photography"] },
  { id:"muktinath", name:"Muktinath Temple", province:"Gandaki Province", category:"heritage", image:"https://images.unsplash.com/photo-1609234656388-0ff363383899?w=800&q=80", description:"One of the most sacred pilgrimage sites in Asia at 3,800 m with 108 stone water spouts and an eternal blue flame.", latitude:28.8167, longitude:83.8667, bestSeason:"Mar–May, Sep–Nov", entryFee:"ACAP permit", activities:["Pilgrimage","Trekking","Photography","High Altitude"] },
  { id:"manaslu", name:"Manaslu Circuit", province:"Gandaki Province", category:"mountain", image:"https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&q=80", description:"A remote trek around the world's 8th highest mountain crossing Larkya La Pass at 5,160 m.", latitude:28.5500, longitude:84.5500, bestSeason:"Sep–Nov, Mar–May", entryFee:"Restricted area permit", activities:["Trekking","Cultural Tours","Photography","High Pass Crossing"] },
  { id:"tilicho", name:"Tilicho Lake", province:"Gandaki Province", category:"lake", image:"https://images.unsplash.com/photo-1445375011782-2384686778a0?w=800&q=80", description:"One of the world's highest lakes at 4,919 m in the Annapurna region with vivid blue-green water.", latitude:28.6833, longitude:83.8000, bestSeason:"Apr–May, Sep–Oct", entryFee:"ACAP permit", activities:["High Altitude Trekking","Photography","Lake Views"] },
  { id:"hadiya", name:"Hadiya, Udayapur", province:"Koshi Province", category:"nature", image:"https://images.unsplash.com/photo-1418065460487-3e41a6c84dc5?w=800&q=80", description:"A hidden gem in the lush green hills of Udayapur district with rich biodiversity and authentic rural Nepali life.", latitude:26.9300, longitude:86.5100, bestSeason:"Oct–Apr", entryFee:"Free", activities:["Nature Walk","Hiking","Village Tour","Local Culture","Photography"] },
  { id:"basaha", name:"Basaha, Udayapur", province:"Koshi Province", category:"nature", image:"https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80", description:"A serene destination in Udayapur surrounded by lush hills, flowing rivers and dense forests perfect for nature lovers.", latitude:26.9500, longitude:86.4800, bestSeason:"Oct–Apr", entryFee:"Free", activities:["Nature Walk","Bird Watching","Village Tour","River Walk","Photography"] }
];

const hotels = [
  { id:"h1", name:"Hotel Yak & Yeti", type:"Luxury Hotel", location:"Durbar Marg, Kathmandu", description:"One of Kathmandu's most iconic luxury hotels set in a heritage building with landscaped gardens and a heated swimming pool.", priceRange:"Luxury (USD 150–300/night)", image:"https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80", rating:4.7 },
  { id:"h2", name:"Temple Tree Resort & Spa", type:"Resort", location:"Lakeside, Pokhara", description:"A beautifully designed resort on the shores of Phewa Lake with direct mountain views and villa-style rooms.", priceRange:"Mid-range (USD 60–120/night)", image:"https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80", rating:4.6 },
  { id:"h3", name:"Namche Green Lodge", type:"Guesthouse", location:"Namche Bazaar, Solukhumbu", description:"A welcoming family-run guesthouse in Namche Bazaar with warm rooms and authentic Sherpa food.", priceRange:"Budget (USD 15–30/night)", image:"https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80", rating:4.5 },
  { id:"h4", name:"Chitwan Jungle Lodge", type:"Eco Lodge", location:"Sauraha, Chitwan", description:"An eco-friendly jungle lodge on the edge of Chitwan National Park built with local materials.", priceRange:"Mid-range (USD 50–90/night)", image:"https://images.unsplash.com/photo-1587381420270-3e1a5b9e6904?w=800&q=80", rating:4.6 },
  { id:"h5", name:"Pokhara Grande Hotel", type:"Luxury Hotel", location:"Baidam, Lakeside Pokhara", description:"Pokhara's premier hotel with panoramic rooftop views of the Annapurna range and an infinity pool.", priceRange:"Luxury (USD 100–200/night)", image:"https://images.unsplash.com/photo-1455587734955-081b22074882?w=800&q=80", rating:4.7 },
  { id:"h6", name:"Bhaktapur Heritage Guesthouse", type:"Guesthouse", location:"Bhaktapur Old City", description:"A charming traditional Newari guesthouse just steps from Durbar Square with rooftop Himalayan views.", priceRange:"Budget (USD 20–45/night)", image:"https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80", rating:4.6 },
  { id:"h7", name:"Club Himalaya Nagarkot", type:"Mountain Resort", location:"Nagarkot, Bhaktapur", description:"Perched on the Nagarkot ridge with uninterrupted sunrise views over Everest, Langtang and the Annapurna range.", priceRange:"Mid-range (USD 70–130/night)", image:"https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800&q=80", rating:4.6 },
  { id:"h8", name:"Bandipur Mountain Lodge", type:"Heritage Guesthouse", location:"Bandipur, Tanahun", description:"A restored Newari-style guesthouse in the car-free hilltop town of Bandipur overlooking terraced valleys.", priceRange:"Budget (USD 25–50/night)", image:"https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=800&q=80", rating:4.7 },
  { id:"h9", name:"Dwarika's Heritage Hotel", type:"Luxury Heritage Hotel", location:"Battisputali, Kathmandu", description:"A living museum of a hotel built from rescued centuries-old carved wood and brick from the Kathmandu Valley.", priceRange:"Luxury (USD 200–400/night)", image:"https://images.unsplash.com/photo-1625244724120-1fd1d34d00f6?w=800&q=80", rating:4.9 },
  { id:"h10", name:"Lumbini Buddha Garden Resort", type:"Resort", location:"Lumbini, Rupandehi", description:"A peaceful resort near the birthplace of Buddha, designed around meditation gardens and lotus ponds.", priceRange:"Mid-range (USD 45–85/night)", image:"https://images.unsplash.com/photo-1583953458882-302655b5c376?w=800&q=80", rating:4.5 }
];

const restaurants = [
  { id:"r1", name:"Bhojan Griha", cuisine:"Traditional Nepali", location:"Dillibazar, Kathmandu", priceRange:"Mid-range", description:"Kathmandu's most celebrated traditional Nepali restaurant inside a 150-year-old Rana palace with folk music performances.", image:"https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80", rating:4.8 },
  { id:"r2", name:"Busy Bee Cafe", cuisine:"Continental & Nepali", location:"Lakeside, Pokhara", priceRange:"Budget", description:"A legendary backpacker cafe on Pokhara's lakeside serving enormous breakfasts and wood-fired pizzas for over 30 years.", image:"https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&q=80", rating:4.5 },
  { id:"r3", name:"OR2K Restaurant", cuisine:"Middle Eastern & Vegetarian", location:"Thamel, Kathmandu", priceRange:"Mid-range", description:"A Thamel institution serving healthy Middle Eastern and vegetarian food in a colourful cushioned lounge.", image:"https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80", rating:4.6 },
  { id:"r4", name:"Thakali Kitchen", cuisine:"Thakali (Mustang-style)", location:"New Road, Kathmandu", priceRange:"Budget", description:"A local favourite serving authentic Thakali cuisine with the best dal bhat in Kathmandu.", image:"https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80", rating:4.7 },
  { id:"r5", name:"Krishnarpan", cuisine:"Royal Nepali Fine Dining", location:"Dwarika's Hotel, Battisputali", priceRange:"Luxury", description:"Nepal's only true fine-dining Nepali restaurant with a ceremonial multi-course meal of up to 22 dishes.", image:"https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80", rating:4.9 },
  { id:"r6", name:"Momos & More", cuisine:"Nepali Street Food", location:"Ason Bazaar, Kathmandu", priceRange:"Budget", description:"A tiny beloved street-food stall serving Kathmandu's most popular momos since 1985.", image:"https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=800&q=80", rating:4.6 },
  { id:"r7", name:"Newa Lahana", cuisine:"Traditional Newari", location:"Bandipur Bazaar, Tanahun", priceRange:"Mid-range", description:"Set inside a 200-year-old Newari house, serving an authentic Newari feast of bara, chatamari and buff choila.", image:"https://images.unsplash.com/photo-1744561249162-c597c1670032?w=800&q=80", rating:4.7 },
  { id:"r8", name:"Sunrise View Restaurant", cuisine:"Nepali & Continental", location:"Nagarkot, Bhaktapur", priceRange:"Mid-range", description:"A large-windowed dining room built to catch the Himalayan sunrise, serving hearty Nepali and continental food.", image:"https://images.unsplash.com/photo-1758243488328-148e39e5e6b1?w=800&q=80", rating:4.5 },
  { id:"r9", name:"Utse Restaurant", cuisine:"Tibetan & Nepali", location:"Thamel, Kathmandu", priceRange:"Budget", description:"A long-standing Thamel favourite serving hearty Tibetan and Nepali comfort food like thukpa and momos.", image:"https://images.unsplash.com/photo-1621293954908-907159247fc8?w=800&q=80", rating:4.5 },
  { id:"r10", name:"Fewa Lakeview Cafe", cuisine:"Nepali & Continental", location:"Lakeside, Pokhara", priceRange:"Budget", description:"A relaxed open-air cafe on the edge of Phewa Lake, popular for slow breakfasts and sunset drinks.", image:"https://images.unsplash.com/photo-1611048267451-e6ed903d4a38?w=800&q=80", rating:4.6 }
];

mongoose.connect(process.env.MONGO_URI).then(async () => {
  console.log('✅ Connected to MongoDB!');

  await Destination.deleteMany();
  await Hotel.deleteMany();
  await Restaurant.deleteMany();
  console.log('🗑️  Old data cleared');

  await Destination.insertMany(destinations);
  console.log('✅ 32 Destinations imported!');

  await Hotel.insertMany(hotels);
  console.log('✅ 10 Hotels imported!');

  await Restaurant.insertMany(restaurants);
  console.log('✅ 10 Restaurants imported!');

  console.log('🎉 All data imported successfully!');
  process.exit();
}).catch(err => {
  console.error('❌ Error:', err);
  process.exit(1);
});
